"""Initial mig

Revision ID: 387d3e3d7d6d
Revises: 
Create Date: 2024-12-07 12:49:14.681117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '387d3e3d7d6d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('pld', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('l', sa.Integer(), nullable=False),
    sa.Column('nr', sa.Integer(), nullable=False),
    sa.Column('pts', sa.Integer(), nullable=False),
    sa.Column('nrr', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standing')
    # ### end Alembic commands ###
